name: nuri & haneul build release files

on:
  push:
    branches:    
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache ~/.stack
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('**/package.yaml') }}
      - name: Download RPython
        uses: actions/checkout@v4
        with:
          repository: mozillazg/pypy
          path: 'pypy'
      - name: Build nuri
        run: stack build --ghc-options -O3
      - name: Test nuri
        run: stack test
      - name: Install nuri
        run: stack install
      - name: Build haneul
        run: python3 ./pypy/rpython/bin/rpython --opt=jit ./haneul/src/target.py
      - name: Upload nuri
        uses: actions/upload-artifact@v4
        with:
          name: nuri Ubuntu binary
          path: ~/.local/bin/nuri
      - name: Upload haneul
        uses: actions/upload-artifact@v4
        with:
          name: haneul Ubuntu binary
          path: ./target-c
  windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache ~/.stack
        uses: actions/cache@v4
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ${{ runner.os }}-${{ hashFiles('**/package.yaml') }}
      - name: Build nuri
        run: stack build --ghc-options -O3
      - name: Test nuri
        run: stack test
      - name: Install nuri
        run: stack install
      - name: Upload nuri
        uses: actions/upload-artifact@v4
        with:
          name: nuri Windows binary
          path: 'C:\Users\runneradmin\AppData\Roaming\local\bin\nuri.exe'
  macos-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download RPython
        uses: actions/checkout@v4
        with:
          repository: mozillazg/pypy
          path: 'pypy'
      - name: Install libffi
        run: brew install libffi
      - name: Install pkg-config 
        run: brew install pkg-config
      - name: Install stack
        run: brew install haskell-stack
      - name: Build nuri
        run: stack build --ghc-options -O3
      - name: Test nuri
        run: stack test
      - name: Install nuri
        run: stack install
      - name: Build haneul
        run: PKG_CONFIG_PATH="/opt/homebrew/Cellar/libffi/3.4.7/lib/pkgconfig/" python3 ./pypy/rpython/bin/rpython --opt=jit ./haneul/src/target.py
      - name: Upload nuri
        uses: actions/upload-artifact@v4
        with:
          name: nuri macOS binary
          path: ~/.local/bin/nuri
      - name: Upload haneul
        uses: actions/upload-artifact@v4
        with:
          name: haneul macOS binary
          path: ./target-c
